# Generated by Django 6.0 on 2026-05-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='電子郵件')),
                ('agree_rules', models.CharField(max_length=100, verbose_name='同意條款')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='借用教師姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='聯絡電話')),
                ('context', models.CharField(blank=True, max_length=100, verbose_name='使用情境')),
                ('course_name', models.CharField(blank=True, max_length=100, verbose_name='課程名稱')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='使用班級')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='使用地點')),
                ('booking_type', models.CharField(max_length=20, verbose_name='預約類型')),
                ('single_date', models.DateField(blank=True, null=True, verbose_name='單次日期')),
                ('single_period', models.CharField(blank=True, max_length=50, verbose_name='單次節次')),
                ('agree_period', models.CharField(blank=True, max_length=10, verbose_name='同意週期規範')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='週期開始')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='週期結束')),
                ('periods_json', models.TextField(blank=True, verbose_name='每週借用節次(JSON)')),
                ('exclude_date', models.CharField(blank=True, max_length=200, verbose_name='排除日期')),
                ('device_type', models.CharField(max_length=20, verbose_name='預約載具類型')),
                ('required_quantity', models.IntegerField(verbose_name='需求總數量')),
                ('special_needs', models.TextField(blank=True, verbose_name='特殊需求')),
                ('pickup_person', models.CharField(blank=True, max_length=50, verbose_name='預計取用人員')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('status', models.CharField(default='借用中', max_length=20, verbose_name='狀態')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('iPad', 'iPad'), ('Chromebook', 'Chromebook'), ('SurfaceGo', 'SurfaceGo'), ('Acer', 'Acer小筆電')], max_length=20, verbose_name='載具類型')),
                ('cart_name', models.CharField(max_length=20, verbose_name='車次/散裝名稱')),
                ('capacity', models.IntegerField(verbose_name='總容量')),
                ('available_qty', models.IntegerField(verbose_name='當前可用數量')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_qty', models.IntegerField(verbose_name='借出數量')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='booking.booking')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.deviceinventory')),
            ],
        ),
    ]
