# Generated by Django 6.0 on 2026-05-21 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='single_period',
        ),
        migrations.RemoveField(
            model_name='deviceinventory',
            name='available_qty',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='結束節次'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='開始節次'),
        ),
        migrations.AlterField(
            model_name='deviceinventory',
            name='capacity',
            field=models.IntegerField(verbose_name='該車總台數'),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_qty', models.IntegerField(verbose_name='分配借出數量')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.booking')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.deviceinventory')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingDetail',
        ),
    ]
